var qDB = [
    {
        'stt': 'Câu 1',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) Công ty sẽ KHÔNG sử dụng lao động nữ làm việc ban đêm, đi công tác xa trong những trường hợp nào?',
        'ans': 'Mang thai từ tháng thứ 7 trở lên, nuôi con nhỏ dưới 1 tuổi',
    },
    {
        'stt': 'Câu 2',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) Điều kiện để lao động nữ được hưởng trợ cấp thai sản từ cơ quan BHXH là có thời gian tham gia BHXH đủ bao nhiêu tháng trong vòng 12 tháng trước khi sinh con?',
        'ans': 'Đủ 6 tháng',
    },
    {
        'stt': 'Câu 3',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) Trường hợp lao động nữ sinh đôi sẽ được nghỉ trước và sau khi sinh con tổng cộng bao nhiêu tháng?',
        'ans': '7 tháng',
    },
    {
        'stt': 'Câu 4',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) NLĐ có hành vi chống đối hoặc khiêu khích, uy hiếp người khác trong công ty sẽ bị xử lý kỷ luật với hình thức nào?',
        'ans': 'Kéo dài thời hạn nâng lương 6 tháng hoặc cách chức',
    },
    {
        'stt': 'Câu 5',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) Tổng mức đóng BHXH, BHYT, BHTN của người lao động và người sử lao động hàng tháng là bao nhiêu % ?',
        'ans': '32%',
    },
    {
        'stt': 'Câu 6',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) NLĐ nữ đang nuôi con nhỏ dưới 1 tuổi và làm việc trong môi trường nặng nhọc độc hại thì mỗi ngày làm việc bao nhiêu giờ?',
        'ans': '6 giờ',
    },
    {
        'stt': 'Câu 7',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    },
    {
        'stt': 'Câu 8',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) Sau khi chấm dứt hợp đồng lao động, người sử dụng lao động phải thanh toán các khoản tiền lương, trợ cấp cho NLĐ trong vòng bao nhiêu ngày?',
        'ans': '14 ngày (làm việc)',
    },
    {
        'stt': 'Câu 9',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) Kể tên các hình thức quấy rối tình dục?',
        'ans': 'Thể chất, lời nói, phi lời nói',
    },
    {
        'stt': 'Câu 10',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) Trợ cấp ốm đau do BHXH chi trả được tính là bao nhiêu phần trăm?',
        'ans': '75%',
    },
    {
        'stt': 'Câu 11',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) Theo quy định công ty, NLĐ đủ bao nhiêu tuổi thì được hưởng các chế độ của người cao tuổi?',
        'ans': 'Nam đủ 60 tuổi, Nữ đủ 55 tuổi',
    },
    {
        'stt': 'Câu 12',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) NLĐ có thâm niên làm việc tại công ty bao lâu thì khi thôi việc sẽ đủ điều kiện xét trợ cấp thôi việc?',
        'ans': 'Đủ 1 năm trở lên',
    },
    {
        'stt': 'Câu 13',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) Trước khi điều động NLĐ sang vị trí công việc khác thì phải thông báo cho NLĐ biết trước bao nhiêu ngày ?',
        'ans': '3 ngày',
    },
    {
        'stt': 'Câu 14',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) NLĐ tự ý xếp hàng tan ca sớm khi chưa được chủ quản đồng ý sẽ bị xử lý kỷ luật bằng hình thức nào?',
        'ans': 'Khiển trách bằng văn bản',
    },
    {
        'stt': 'Câu 15',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) NLĐ nam có vợ sinh mổ thì sẽ được nghỉ phép thai sản nam bao nhiêu ngày?',
        'ans': '7 ngày (làm việc)',
    },
    {
        'stt': 'Câu 16',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) Chứng từ để xác nhận tai nạn giao thông được tính là tai nạn lao động gồm những chứng từ nào?',
        'ans': 'Biên bản xác nhận của công an, chứng từ của cơ sở y tế',
    },
    {
        'stt': 'Câu 17',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) Hãy kể tên các loại phép hưởng nguyên lương mà công ty đang áp dụng?',
        'ans': 'Phép năm, phép cưới, phép tang, phép tai nạn lao động',
    },
    {
        'stt': 'Câu 18',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) Trường hợp NLĐ sinh con phẫu thuật thì được nghỉ dưỡng sức bao nhiêu ngày?',
        'ans': '7 ngày',
    },

    {
        'stt': 'Câu 19',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) Theo quy định công ty, khi hợp đồng lao động sắp hết hạn, công ty không muốn tiếp tục ký hợp đồng với người lao động thì phải báo trước bao nhiêu ngày? ',
        'ans': '15 ngày',
    },
    {
        'stt': 'Câu 20',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) NLĐ bị kỷ luật kéo dài thời hạn nâng lương 6 tháng, nếu tái phạm trong vòng bao nhiêu tháng thì sẽ bị sa thải?',
        'ans': '3 tháng',
    },
    {
        'stt': 'Câu 21',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) NLĐ không thành thật khai báo thực trạng công việc thì sẽ bị xử lý kỷ luật bằng hình thức nào?',
        'ans': 'Khiển trách bằng văn bản',
    },
    {
        'stt': 'Câu 22',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) NLĐ không tuân thủ theo quy định của bảo vệ, từ chối để bảo vệ kiểm tra thì sẽ bị xử lý kỷ luật bằng hình thức nào?',
        'ans': 'Khiển trách bằng văn bản',
    },
    {
        'stt': 'Câu 23',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) Giá trị cốt lõi của công ty là gì?',
        'ans': 'Vui vẻ, phát triển, trách nhiệm',
    },
    {
        'stt': 'Câu 24',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) NLĐ tăng ca liên tục từ 2h trở lên sẽ được hưởng các khoản phúc lợi nào?',
        'ans': 'Tiền ăn 15,000 VND và được tính thêm 0.5h tăng ca',
    },
    {
        'stt': 'Câu 25',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) Trước khi tan ca, NLĐ không thu dọn thiết bị dụng cụ thì sẽ bị xử lý kỷ luật bằng hình thức nào? ',
        'ans': 'Khiển trách bằng miệng',
    },
    {
        'stt': 'Câu 26',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    },
    {
        'stt': 'Câu 27',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    },
    {
        'stt': 'Câu 28',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    },
    {
        'stt': 'Câu 29',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    },
    {
        'stt': 'Câu 30',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    },
    {
        'stt': 'Câu 31',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    },
    {
        'stt': 'Câu 32',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    },
    {
        'stt': 'Câu 33',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    },
    {
        'stt': 'Câu 34',
        'img': "./static/bongbong.png",
        'q': '(7 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    },
    {
        'stt': 'Câu 35',
        'img': "./static/bongbong.png",
        'q': '(8 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    },
    {
        'stt': 'Câu 36',
        'img': "./static/bongbong.png",
        'q': '(6 điểm) NLĐ làm việc theo ca được nghỉ ít nhất bao nhiêu giờ trước khi chuyển sang ca làm việc khác?',
        'ans': '12 giờ',
    }
];